services:
  db:
    image: postgres
    volumes:
      - /data/coolify/applications/as8w0cc/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    container_name: signal_bot_db

  signal-cli:
    image: registry.gitlab.com/packaging/signal-cli/signal-cli-native:latest
    command: "daemon --http 0.0.0.0:7583"
    ports:
      - "7583:7583"
    volumes:
      - "/data/coolify/applications/as8w0cc/signal_config/:/var/lib/signal-cli/"
    tmpfs:
      - "/data/coolify/applications/as8w0cc/tmp:exec"

  web:
    build: ./server
    ports:
      - 8015:8000
    image: signal_bot:middleware
    container_name: signal_bot_db_middleware
    volumes:
      - "/data/coolify/applications/as8w0cc/static/:/app/static/"
      - "/data/coolify/applications/as8w0cc/media/:/app/media/"
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    stdin_open: true
    tty: true
    depends_on:
      - signal-cli

  sse-client:
    build: ./sse_client
    networks:
      - signal-notifier
    image: signal_bot:sse_client
    container_name: signal_bot_sse_client
    command: python client.py
    depends_on:
      - web
      - signal-cli
