# Generated by Django 4.2.10 on 2024-05-27 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignalGroup',
            fields=[
                ('name', models.CharField(max_length=255, verbose_name='Group Name')),
                ('signal_id', models.CharField(max_length=255, verbose_name='Signal ID')),
                ('internal_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Internal ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Model created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Model modified at')),
            ],
        ),
        migrations.CreateModel(
            name='SignalUser',
            fields=[
                ('display_name', models.CharField(max_length=255, verbose_name='Display Name')),
                ('source_name', models.CharField(max_length=255, verbose_name='Source Name')),
                ('source_number', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Source Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Model created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Model modified at')),
                ('is_registered', models.BooleanField(default=False, verbose_name='I a Registered user')),
            ],
        ),
        migrations.CreateModel(
            name='SignalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(verbose_name='Text content')),
                ('raw_content', models.JSONField(null=True, verbose_name='Raw content')),
                ('is_incoming', models.BooleanField(verbose_name='Is incoming')),
                ('received_at', models.DateTimeField(verbose_name='Message received at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Model created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Model modified at')),
                ('source_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_messages', to='core.signaluser', verbose_name='Source User')),
                ('target_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_messages', to='core.signalgroup', verbose_name='Source Group')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_messages', to='core.signaluser', verbose_name='Source User')),
            ],
        ),
        migrations.AddField(
            model_name='signalgroup',
            name='members',
            field=models.ManyToManyField(related_name='groups', to='core.signaluser'),
        ),
        migrations.AddField(
            model_name='signalgroup',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_groups', to='core.signaluser'),
        ),
        migrations.AddConstraint(
            model_name='signalmessage',
            constraint=models.UniqueConstraint(fields=('target_group', 'source_user', 'target_user', 'received_at'), name='unique_together_group_user_received'),
        ),
    ]
