# Generated by Django 4.2.10 on 2024-05-27 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalmessage',
            name='target_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_messages', to='core.signaluser', verbose_name='Source User'),
        ),
        migrations.AddConstraint(
            model_name='signalmessage',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(('target_group__isnull', False), ('target_user__isnull', True)), models.Q(('target_group__isnull', True), ('target_user__isnull', False)), _connector='OR')), name='only_one_target_allowed', violation_error_message='Only one of target_group and target_user field can be set'),
        ),
    ]
