# Generated by Django 4.2.10 on 2024-06-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='longitude',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=10, verbose_name='longitude'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forecast',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=9, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='segment_datetime',
            field=models.DateTimeField(unique=True, verbose_name='segment datetime'),
        ),
    ]
