# Generated by Django 4.2.10 on 2024-06-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_bot', '0002_forecast_longitude_alter_forecast_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherAlertCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_operand', models.CharField(max_length=255, verbose_name='right operand')),
                ('operator', models.CharField(choices=[('exact', 'Equal'), ('gt', 'Greater than'), ('gte', 'Greater than or equal'), ('lt', 'Lesser than'), ('lte', 'Lesser than or equal'), ('icontains', 'Contains')], default='exact', max_length=255, verbose_name='right operand')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherAlertConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=9, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='longitude')),
            ],
        ),
        migrations.AlterField(
            model_name='forecast',
            name='segment_datetime',
            field=models.DateTimeField(verbose_name='segment datetime'),
        ),
        migrations.AddIndex(
            model_name='forecast',
            index=models.Index(fields=['latitude', 'longitude'], name='weather_bot_latitud_b38bf2_idx'),
        ),
        migrations.AddConstraint(
            model_name='forecast',
            constraint=models.UniqueConstraint(fields=('segment_datetime', 'latitude', 'longitude'), name='unique_for_time_and_place'),
        ),
        migrations.AddIndex(
            model_name='weatheralertconfiguration',
            index=models.Index(fields=['latitude', 'longitude'], name='weather_bot_latitud_8d6e64_idx'),
        ),
    ]
