# Generated by Django 4.2.10 on 2024-06-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_bot', '0002_forecast_longitude_alter_forecast_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='segment_datetime',
            field=models.DateTimeField(verbose_name='segment datetime'),
        ),
        migrations.AddConstraint(
            model_name='forecast',
            constraint=models.UniqueConstraint(fields=('segment_datetime', 'latitude', 'longitude'), name='unique_for_time_and_place'),
        ),
    ]
